# Text Representation

Text representation in NLP means converting text into a numerical form that a machine learning model can understand and process.

## What is Embedding?

Embeddings in NLP is a technique where individual words are represented as real-valued vectors and captures inter-word semantics.


In this notebook, We going to intreduce 2 techniques for embedding. These techniques will be used for a machine learning models such as SVM, Random forest, ... ect.

<img src="https://drive.google.com/uc?export=view&id=1jd0u_sGppDKqBYbhtJfGxp14lnUWUTTw" width="900">

# 1- TF-IDF

<img src="https://drive.google.com/uc?export=view&id=1saSt0mMgOQ2ybbTms1lu_ruhUcBWkKzL" width="500">

TF-IDF stands for term frequency-inverse document frequency. It is a measure that discounts common words. Used in the fields of information retrieval (IR) and machine learning, that can quantify the importance of words in a document amongst a collection of documents (also known as a corpus).

### Components of TF-IDF

1. **TF (Term Frequency):**  
   Measures how frequently a term appears in a document.


$$ \text{TF}(t, d) = \frac{\text{Number of times term } t \text{ appears in document } d}{\text{Total number of terms in document } d} $$


2. **IDF (Inverse Document Frequency):**  
   Measures how important a term is across all documents. Words that appear in many documents get lower scores.

$$    \text{IDF}(t) = \log \left(\frac{\text{Number of all documents N}}{\text{Number of documents containing the term } t}\right) $$

<img src="https://drive.google.com/uc?export=view&id=1JqPILC8TTh3yDQZCSuPNXwm6ER5YeJFh" width="900">

In [1]:
import sys

print(sys.executable)

C:\Users\HUAWEI\.conda\envs\cosine-env\python.exe

In [2]:
import numpy
import pandas
import scipy
import sklearn

print("NumPy:", numpy.__version__)
print("Pandas:", pandas.__version__)
print("SciPy:", scipy.__version__)
print("Scikit-learn:", sklearn.__version__)

NumPy: 2.5.3
Pandas: 3.0.6
SciPy: 1.18.1
Scikit-learn: 1.9.1

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [4]:
doc_1 = "Data is the oil of the digital economy"
doc_2 = "Data is a new oil"

data = [doc_1, doc_2]

In [5]:
tfidf = TfidfVectorizer()
result = tfidf.fit_transform(data) # returns sparce matrix

In [7]:
import pandas as pd
df = pd.DataFrame(result.toarray(), columns=tfidf.get_feature_names_out())
df

       data  digital  economy        is       new       of       oil      the
0  0.243777  0.34262  0.34262  0.243777  0.000000  0.34262  0.243777  0.68524
1  0.448321  0.00000  0.00000  0.448321  0.630099  0.00000  0.448321  0.00000

# Cosine similarity

In NLP, Cosine similarity is a metric used to measure how similar the documents are.


$$ \text{cosine similarity} = \frac{A \cdot B}{\|A\| \times \|B\|} $$

Where:  
$ A \cdot B $  = dot product of vectors A and B  
$ \|A\| $ = magnitude (length) of vector A  
$ \|B\| $ =  magnitude (length) of vector B

#### Intuition

- If vectors point in the **same direction**, cosine similarity = **1** (maximum similarity).
- If vectors are **orthogonal (90° apart)**, cosine similarity = **0** (no similarity).

<img src="https://drive.google.com/uc?export=view&id=1b-o8CVfHBsjUGY_hXmxevU91gHidIuxO" width="900">

In [8]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [9]:
# Sample text data (replace with your own documents)

doc_1 = "Data is the oil of the digital economy"
doc_2 = "Data is a new oil"

data = [doc_1, doc_2]

In [10]:
tfidf_vectorizer = TfidfVectorizer() # Create a CountVectorizer instance
vector_matrix = tfidf_vectorizer.fit_transform(data) # Fit and transform the documents into numerical vectors

In [11]:
# Calculate the cosine similarity between the documents
cosine_similarity_matrix = cosine_similarity(vector_matrix)

df_cosine = pd.DataFrame(data=cosine_similarity_matrix, index=data, columns=data)

df_cosine

,Data is the oil of the digital economy,Data is a new oil
Data is the oil of the digital economy,1.000000,0.327871
Data is a new oil,0.327871,1.000000

# 2- What is Word2vec?

Word2Vec consists of models for generating word embedding. These models are two-layer neural networks having one input layer, one hidden layer, and one output layer.

Word2Vec utilizes two architectures :
1. CBOW (Continuous Bag of Words)
2. **Skip Gram**
<img src="https://drive.google.com/uc?export=view&id=1K38nEu_KhgtSJuG2RySwc6U5AAjVAgWZ" width="600">


Run this command in terminal to install
> pip install gensim

We will use fake and real news dataset to do our expirament. You can find the dataset here: https://www.kaggle.com/datasets/clmentbisaillon/fake-and-real-news-dataset?select=True.csv

In [13]:
%pip install nltk

Collecting nltk
  Downloading nltk-3.10.3-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: defusedxml in C:\Users\HUAWEI\.conda\envs\cosine-env\Lib\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in C:\Users\HUAWEI\AppData\Roaming\Python\Python312\site-packages (from nltk) (8.5.0)
Requirement already satisfied: joblib in C:\Users\HUAWEI\AppData\Roaming\Python\Python312\site-packages (from nltk) (1.6.0)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.9.10-cp312-cp312-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk)
  Downloading tqdm-4.70.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: cloudpickle>=3.0 in C:\Users\HUAWEI\AppData\Roaming\Python\Python312\site-packages (from joblib->nltk) (3.1.2)
Requirement already satisfied: colorama in C:\Users\HUAWEI\AppData\Roaming\Python\Python312\site-packages (from tqdm->nltk) (0.4.6)
Downloading nltk-3.10.3-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----------------- ---------------------- 0.8/1.8 MB 1.6 MB/s eta 0:00:01
   ----------------------------- ---------- 1.3/1.8 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 1.9 MB/s  0:00:01
Downloading regex-2026.9.10-cp312-cp312-win_amd64.whl (277 kB)
Downloading tqdm-4.70.1-py3-none-any.whl (80 kB)
Installing collected packages: tqdm, regex, nltk

   ---------------------------------------- 0/3 [tqdm]
   ---------------------------------------- 0/3 [tqdm]
   ------------- -------------------------- 1/3 [regex]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   ---------------------------------------- 3/3 [nltk]

Successfully installed nltk-3.10.3 regex-2026.9.10 tqdm-4.70.1
Note: you may need to restart the kernel to use updated packages.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spacy 3.8.16 requires pydantic<3.0.0,>=2.0.0, which is not installed.

In [15]:
%pip install smart-open

Collecting smart-open
  Downloading smart_open-8.0.1-py3-none-any.whl.metadata (24 kB)
Collecting wrapt (from smart-open)
  Downloading wrapt-2.4.1-cp312-cp312-win_amd64.whl.metadata (7.6 kB)
Downloading smart_open-8.0.1-py3-none-any.whl (73 kB)
Downloading wrapt-2.4.1-cp312-cp312-win_amd64.whl (98 kB)
Installing collected packages: wrapt, smart-open

   ---------------------------------------- 0/2 [wrapt]
   -------------------- ------------------- 1/2 [smart-open]
   ---------------------------------------- 2/2 [smart-open]

Successfully installed smart-open-8.0.1 wrapt-2.4.1
Note: you may need to restart the kernel to use updated packages.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.21.0 requires h5py<3.15.0,>=3.11.0, which is not installed.
weasel 1.0.0 requires pydantic>=2.0.0, which is not installed.

In [16]:
import pandas as pd
import nltk
import numpy as np
import gensim

from nltk.tokenize import word_tokenize

In [17]:
df = pd.read_csv('True.csv', engine='python', on_bad_lines='skip') #fake-and-real-news-dataset-true.csv
df.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [19]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\HUAWEI\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [20]:
tokens = []

for i in df['text']:
    token = word_tokenize(i)
    tokens.append(token)

In [21]:
w2v = gensim.models.Word2Vec(tokens, min_count=1, vector_size=100, window=5, sg=1)

In [22]:
print("Cosine similarity between 'provide' and 'program' - Skip Gram : ",w2v.wv.similarity('provide', 'program'))

Cosine similarity between 'provide' and 'program' - Skip Gram :  0.43307877

In [23]:
print("words that similar to 'program' - Skip Gram : ",w2v.wv.most_similar('program'))

words that similar to 'program' - Skip Gram :  [('programme', 0.807282567024231), ('programs', 0.7961248159408569), ('bond-buying', 0.6928004622459412), ('restraints', 0.6904298067092896), ('programmes', 0.6829302310943604), ('curbed', 0.6805152297019958), ('modernization', 0.6724158525466919), ('arsenal', 0.6694204211235046), ('curtail', 0.6688202023506165), ('Deferred', 0.665593683719635)]

# Tasks

### Task 1: Cosine Similarity
Use the Cosine Similarity method to determine how similar the following sentences are.

'This is the first document.',  
'This document is the second document.',  
'And this is the third one.',  
'Is this the first document?'

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sen= [
    "This is the first document.",
    "This document is the second document.",
    "And this is the third one.",
    "Is this the first document?"
]

# convert sentences to Bag of Words vectors
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(sen)

print("Vocab:")
print(vectorizer.get_feature_names_out())

Vocab:
['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']

### Task 2: TF-IDF
Use tf-idf method on the sentences below to determine the important words.

'data science is one of the most important fields of science',  
'this is one of the best data science courses',  
'data scientists analyze data'

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

# Sentences
sentences = [
    'data science is one of the most important fields of science',
    'this is one of the best data science courses',
    'data scientists analyze data'
]

# Create TF-IDF vectorizer
vectorizer = TfidfVectorizer()

# Calculate TF-IDF
tfidf_matrix = vectorizer.fit_transform(sentences)

# Get the words
words = vectorizer.get_feature_names_out()

# Display TF-IDF values
df_tfidf = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=words,
    index=['Sentence 1', 'Sentence 2', 'Sentence 3']
)

print(df_tfidf.round(3))

            analyze  best  courses   data  fields  important     is   most  \
Sentence 1    0.000   0.0      0.0  0.190   0.321      0.321  0.244  0.321
Sentence 2    0.000   0.4      0.4  0.236   0.000      0.000  0.304  0.000
Sentence 3    0.543   0.0      0.0  0.641   0.000      0.000  0.000  0.000

               of    one  science  scientists    the  this
Sentence 1  0.488  0.244    0.488       0.000  0.244   0.0
Sentence 2  0.304  0.304    0.304       0.000  0.304   0.4
Sentence 3  0.000  0.000    0.000       0.543  0.000   0.0

In [26]:
# determine important words
for sentence, row in df_tfidf.iterrows():
    print(f"\n{sentence}:")
    print(row[row > 0].sort_values(ascending=False))

Sentence 1:
science      0.488098
of           0.488098
most         0.320895
fields       0.320895
important    0.320895
one          0.244049
is           0.244049
the          0.244049
data         0.189526
Name: Sentence 1, dtype: float64

Sentence 2:
best       0.400294
courses    0.400294
this       0.400294
of         0.304434
is         0.304434
science    0.304434
one        0.304434
the        0.304434
data       0.236420
Name: Sentence 2, dtype: float64

Sentence 3:
data          0.641055
analyze       0.542701
scientists    0.542701
Name: Sentence 3, dtype: float64

## Word2vec

### Task 3:

Download the Simpsons dataset **(simpsons_script_lines.csv)** and apply the preprocessing procedure.  
Use the **'spoken_words'** column.
```
def clean_text(text):
    text = text.lower()
    text = re.sub(r"[0-9]", '', text)
    text = re.sub(r"[)(,”“.’$-]", '', text)
    return text
```
Create a skip gram Word2Vec model as below.
```
Skip_gram_model = gensim.models.Word2Vec(tokens, min_count = 1, vector_size = 100, window = 5, sg = 1)

In [28]:
import pandas as pd
import re
import nltk
import gensim
from nltk.tokenize import word_tokenize

# Load dataset
df = pd.read_csv("simpsons_script_lines.csv")

# Select spoken_words
df = df[['spoken_words']]

# Remove missing values
df = df.dropna()

# Preprocessing
def clean_text(text):
    text = text.lower()
    text = re.sub(r"[0-9]", '', text)
    text = re.sub(r"[)(,”“.’$-]", '', text)
    return text

# Clean text
df['cleaned_text'] = df['spoken_words'].apply(clean_text)

# Tokenization
tokens = []

for text in df['cleaned_text']:
    token = word_tokenize(text)
    tokens.append(token)

# Create Skip-Gram Word2Vec model
Skip_gram_model = gensim.models.Word2Vec(
    tokens,
    min_count=1,
    vector_size=100,
    window=5,
    sg=1
)

# Check word vector
print("Homer vector:")
print(Skip_gram_model.wv['homer'])

# Find similar words
print("\nWords similar to Homer:")
print(Skip_gram_model.wv.most_similar('homer'))

Homer vector:
[-0.07602011 -0.22398715 -0.04749445 -0.26327556  0.3612373   0.06594434
  0.24462283  0.81667066 -0.59662694 -0.39868107 -0.08317615 -0.7901254
  0.18451394  0.36149842  0.6386135  -0.19318713 -0.17030434 -0.3720579
 -0.26547816 -0.82069147  0.181214    0.18595165  0.6421635  -0.0244816
 -0.25457618 -0.20036377 -0.36349213  0.06561455 -0.54988766 -0.16259208
 -0.501878   -0.13421504 -0.04420707 -0.3465114  -0.17268285  0.44474822
  0.07768079  0.10474642 -0.20948698 -0.12738954  0.14721623 -0.27827683
 -0.07949102  0.05711335  0.45251042 -0.22238918 -0.6014628  -0.04606032
  0.04970681  0.12064264 -0.5663171  -0.16551177 -0.19090298 -0.24228463
  0.26064748 -0.1120339   0.5192152   0.19663396 -0.26461947  0.48328316
 -0.05643733 -0.01932562  0.604515    0.4043045  -0.08256321  0.17657192
  0.7396954   0.6741843  -0.28991494  0.32630667 -0.18037899  0.6398672
  0.08706747 -0.03664925  0.25231135 -0.1267026  -0.18578744 -0.03403939
 -0.3814957  -0.46653214 -0.15405199  0.08837114 -0.3076467   0.5682042
 -0.402098    0.3664688   0.49289763  0.3138292   0.24299817  0.1643634
  0.46744412 -0.05138572  0.299277    0.2869655   0.3434117   0.1301867
  0.3890046  -0.18137453  0.3200091  -0.19345303]

Words similar to Homer:
[('abe', 0.8729132413864136), ('marge', 0.849003791809082), ('apu', 0.8126168847084045), ('allison', 0.8065533638000488), ('bart', 0.8055281639099121), ('bartholomew', 0.8050535321235657), ('eliza', 0.8020887970924377), ('mindy', 0.7943410873413086), ('mister', 0.7941898703575134), ('monty', 0.7895318865776062)]

### Task 4

Use: wv.most_similar() method to :

1.	Find the words similar to “homer”.

2.	Find the words similar to “marge”.

3. Find the words similar to “bart”

In [29]:
# Task 4: Find similar words

# 1. Words similar to "homer"
print("Words similar to 'homer':")
print(Skip_gram_model.wv.most_similar("homer"))


# 2. Words similar to "marge"
print("\nWords similar to 'marge':")
print(Skip_gram_model.wv.most_similar("marge"))


# 3. Words similar to "bart"
print("\nWords similar to 'bart':")
print(Skip_gram_model.wv.most_similar("bart"))

Words similar to 'homer':
[('abe', 0.8729132413864136), ('marge', 0.849003791809082), ('apu', 0.8126168847084045), ('allison', 0.8065533638000488), ('bart', 0.8055281639099121), ('bartholomew', 0.8050535321235657), ('eliza', 0.8020887970924377), ('mindy', 0.7943410873413086), ('mister', 0.7941898703575134), ('monty', 0.7895318865776062)]

Words similar to 'marge':
[('homer', 0.849003791809082), ('abe', 0.844673216342926), ('sweetie', 0.8262770175933838), ('sweetheart', 0.8118306398391724), ('becky', 0.8100406527519226), ('allison', 0.80571448802948), ('honey', 0.8048762083053589), ('apu', 0.8044027090072632), ('midge', 0.8020246624946594), ('lis', 0.7998860478401184)]

Words similar to 'bart':
[('milhouse', 0.8652418851852417), ('lisa', 0.8448435068130493), ('jessica', 0.8375933766365051), ('allison', 0.8362329602241516), ('grampa', 0.836094319820404), ('eliza', 0.8302003145217896), ('saxophone', 0.8240002989768982), ('stampy', 0.8207791447639465), ('laddie', 0.819612979888916), ('janey', 0.8165731430053711)]

### Task 5

Use the wv.doesnt_match() method to :

1.	Find which of 'jimbo', 'milhouse’, and 'kearney’ does not belong to the list.

3.	Find the odd one among "nelson", "bart", and "milhouse".

4.	Find the odd one among ‘homer', 'patty', and ‘selma'.

*Hint: You need to pass the strings as List*

In [30]:
# Task 5: Find the odd word

# 1. Find the word that does not belong
result1 = Skip_gram_model.wv.doesnt_match(
    ['jimbo', 'milhouse', 'kearney']
)

print("1. Odd word:", result1)


# 2. Find the odd word
result2 = Skip_gram_model.wv.doesnt_match(
    ['nelson', 'bart', 'milhouse']
)

print("2. Odd word:", result2)


# 3. Find the odd word
result3 = Skip_gram_model.wv.doesnt_match(
    ['homer', 'patty', 'selma']
)

print("3. Odd word:", result3)

1. Odd word: milhouse
2. Odd word: nelson
3. Odd word: homer